prgrms-web-devcourse/Team-BackFro-ArtZip-FE

- .husky/pre-commit
**급한 부분이니 리뷰 받으면 바로 머지하겠습니다!**
close #40
> fix: .husky 설정 파일의 오타 수정

- components/molecule/index.ts
- components/organism/Swiper/index.tsx
- components/organism/Swiper/style.ts
- package.json
- pages/_app.tsx
- pages/index.tsx
- public/mockServiceWorker.js
- yarn.lock
https://user-images.githubusercontent.com/72402747/182035453-4155ee56-041d-4b8c-b282-082fd4263149.mov
저 prettier가 안 먹는 거 같네요 ... ? 🥲
close #8
> feat: Swiper 구현

- components/molecule/ExhibitionCard/index.tsx
- types/apis/base.ts
- types/apis/comment/index.ts
- types/apis/exhibition/index.ts
- types/apis/user/index.ts
- types/model.ts
> feat: api interface 정의

- mocks/handlers/comment/index.ts
- mocks/handlers/review/index.ts
> test: comment 관련 mock 데이터 생성

- pages/signin/index.tsx
https://user-images.githubusercontent.com/93373357/182808210-cf4a18c9-fae1-4a5c-be7a-6f221d9c4bda.mp4
https://user-images.githubusercontent.com/93373357/182808238-8b817bb9-124d-4c99-a6c3-46dca06d879f.mp4
아직 validation이나 submit  구현 안 한 상태입니당
로고나 카카오 이미지 등도 임시로 넣은 부분이니 신경 쓰지 마시고 마크업만 봐주시길 바랍니당
close #87
> feat: 로그인 페이지 마크업

- components/molecule/ScrollButton/index.tsx
- components/molecule/index.ts
- 위 아래 이동 버튼을 구현하였습니다.
대충 레이아웃에 버튼만 끼워넣은 형태입니다. 동작과 디자인만 봐주세요!
- 디자인에 대한 피드백 부탁드립니다!
- 이 후에 이 버튼을 어디다가 넣을지 (기본 레이아웃에 넣을지?)를 함께 논의해봐야할 것 같습니다. 디자인적으로 다른게 생길지도 모르겠다는 생각이 드네요!
close #68
> feat: ScrollButton 컴포넌트 구현

- components/molecule/UserInfo/index.tsx
- components/organism/InfoGroup/index.tsx
- components/organism/ReviewFeed/index.tsx
- mocks/handlers/review/index.ts
- pages/community/index.tsx
- types/apis/review/index.ts
- types/model.ts
> feat: 커뮤니티 페이지 구현

- components/molecule/ExhibitionCard/index.tsx
- components/molecule/ExhibitionCard/style.ts
- pages/index.tsx
- types/model.ts
https://user-images.githubusercontent.com/72402747/182851191-efa19415-46e9-4cb2-baa5-8f1a3faddc6f.mov
close #101
> feat: Exhibition Card 커스텀

- mocks/handlers/comment/index.ts
> test : comment API 모킹

- components/organism/ReviewDetail/index.tsx
- mocks/handlers/comment/index.ts
- mocks/handlers/review/index.ts
- pages/reviews/detail/[id]/index.tsx
- types/apis/review/index.ts
타입만 수정하였으므로 바로 머지하겠습니다.
close #116
> fix: api 명세 수정에 따른 타입 수정

- components/organism/SearchToolbar/style.ts
- pages/exhibitions/custom/index.tsx
- pages/exhibitions/more/index.tsx
- pages/index.tsx
- pages/search-result/index.tsx
- styles/pages/exhibitionsCustom.ts
페이지네이션 부분이라 서버통신을 붙이고 나서 디테일한 css를 잡게 될 거 같습니다 🙃 우선은 이만큼만 올려두겠습니다 !!! 
close #96
> feat: 맞춤페이지 마크업

- apis/common.ts
인증이 필요한 요청(authRequest)에서
headers에 ACCESS_TOKEN을 보내는 코드를 수정했습니다. 
왼쪽이 오른쪽으로 바뀌웠습니다. 
급한 이슈이므로 1~2시간 뒤에 머지하겠습니다. 
close #132
> refactor: authRequest의 토큰 전달 수정

- pages/signin/index.tsx
- utils/cookie/index.ts
- utils/index.ts
- utils/storage/index.ts
> feat: 액세스 토큰/리프레시 토큰 만료 기간 설정

- components/molecule/ExhibitionCard/index.tsx
- components/organism/Swiper/index.tsx
- next.config.js
- pages/index.tsx
> feat: 메인페이지 서버통신 구현

- apis/exhibition/index.ts
- pages/exhibitions/custom/index.tsx
- styles/pages/exhibitionsCustom.ts
동영상을 올리고 싶은데 용량이 커져서 번거로우시겠지만 브랜치에 직접 들어와서 확인 부탁드려용 ~~ 🥺
close #149
> feat: 맞춤 전시회 페이지 서버통신 구현

- apis/user/index.ts
- components/molecule/SideNavigation/index.tsx
- components/organism/Header/index.tsx
- hooks/useUserAuthActions/index.ts
- pages/users/[id]/edit-password/index.tsx
- pages/users/[id]/edit/index.tsx
로그아웃은 정상적으로 되고 있으나, 그 외 이슈가 약간 발생했습니다. 
로그인 한 상태에서 앱을 종료 => 이후 앱을 다시 켤 때 에러 발생 
"서버에서 내려주는 정보와 브라우저의 정보가 일치하지 않는다"
서버에서는 내려 주는 정보
클라이언트에서는 인식하는 정보
현재 userId라는 변수로 로그인 여부를 판단하고 있습니다. 
서버에서는 userId가 null입니다. 쿠키의 토큰 값 존재 여부는 알 수 없습니다. 
브라우저에서는 userId가 null이 아니고, 쿠키의 토큰 값이 그대로 존재합니다. 
이 문제를 해결하려면 userId가 아니라 
쿠키에서 토큰 값을 꺼내와 로그인 여부를 판단해야 할 것 같습니다. 
확실하진 않군요. 
더군다나 이것은 임시방편이고, 
좀 더 근본적인 해결방법이 있지 않을까 생각합니다. 
관련 링크입니다. 
https://nextjs.org/docs/messages/react-hydration-error
close #159
> feat: 로그아웃 구현

- pages/exhibitions/more/index.tsx
현재 선택한 페이지 번호에 따라 요청을 보내는데 현재 데이터가 좀 중복되어서 오는 것 같습니다 !! 🫠
제리랑 이야기해볼게용 ?
- 참고
https://server.artzip.shop/api/v1/exhibitions/mostlike?page=1&size=8
https://server.artzip.shop/api/v1/exhibitions/mostlike?page=2&size=8
https://server.artzip.shop/api/v1/exhibitions/mostlike?page=3&size=8
close #146
> feat: 더보기페이지 서버통신 구현

- components/organism/Header/index.tsx
- hooks/useClickAway/index.ts
- pages/reviews/create/index.tsx
- pages/users/[id]/index.tsx
- styles/globals.css
배포 시, 유저 페이지 및 헤더에서 발생한 버그를 수정했습니다. 
close #174
> fix: 유저 페이지 및 헤더의 버그 수정

- apis/comment/index.ts
- apis/common.ts
- apis/review/index.ts
- components/organism/CommentList/index.tsx
- components/organism/CommentUtils/index.tsx
- components/organism/CommentWrite/index.tsx
- components/organism/Header/index.tsx
- components/organism/ReplyUtils/index.tsx
- components/organism/index.ts
- constants/index.ts
- constants/userLoginState.ts
- hooks/useUserAuthActions/index.ts
- pages/_app.tsx
- pages/community/index.tsx
- pages/reviews/detail/[id]/index.tsx
- states/user.ts
- styles/globals.css
- types/model.ts
급하게 구현하느라 코드를 정리하지 못했습니다. 죄송합니다 ㅠㅠ
동작 위주로 봐주세요!
- API, 인증 관련
- 댓글 관련 [feat: 댓글에 대한 CRUD 로직 구현](https://github.com/prgrms-web-devcourse/Team-BackFro-ArtZip-FE/commit/75a38faeb3fe356308b1c8423a66bb5761c5da9f)
- 댓글 무한 스크롤 (렌더링 이상한건 **논의하고 싶은 부분** 참고)
- 댓글 좋아요
- 댓글 작성, 수정, 삭제
- 대댓글 작성, 수정, 삭제
- 대댓글 무한 스크롤
- 처음 댓글 불러오는 값의 정렬 방식과, 다시 받아올 때의 정렬 방식이 다르네요(처음 불러올 때는 오래된 순으로 불러와지고, 다시 받아올 때는 최신순으로 불러옵니다.)
그래서 ... 에밀리에게 요청 해야 할 것 같습니다 ㅠㅠ 시간이 얼마 남지 않아 해당 로직이 불가능하다면 `useEffect`를 돌려보겠습니다..
- 댓글 수도 마찬가지로... commentCount에 대한 요청이 필요하다고 느끼고, 만약 시간상 부족하다면 디테일 조회에서는 댓글 갯수를 빼야할 것 같습니다. (이 값을 위해 매번 리뷰 상세 조회를 새로 해야 합니다)
- 
close #152
> feat: 댓글 관련 기능 구현

- components/molecule/ReviewCard/index.tsx
- hooks/useUserAuthActions/index.ts
- pages/exhibitions/detail/[id]/index.tsx
- styles/pages/exhibitionsStyle.ts
- types/apis/exhibition/index.ts
> feat: 리뷰 컨테이너 수정 

- hooks/useUserAuthActions/index.ts
- next.config.js
- pages/_app.tsx
- pages/index.tsx
- utils/tokenManager/index.ts
> hotfix: 배포 테스트

- apis/exhibition/index.ts
- components/organism/SearchToolbar/index.tsx
- constants/exhibitionGenre.ts
- constants/index.ts
- pages/exhibitions/custom/index.tsx
> feat: 맞춤전시회 장르 추가

- pages/exhibitions/more/index.tsx
- pages/search-result/index.tsx
검색한 exhibition이 string 또는 string[] 이라고 하여서 `string` 일 때만 받기로 하였습니다! 
close #171
> feat: 검색결과 서버통신 구현

- components/organism/ReviewFeed/style.ts
> design: reviewFeed 줄바꿈 속성 추가

- components/organism/ExhibitionDetail/index.tsx
- pages/signin/index.tsx
This reverts commit 04ee5739389fc88bd481bc44e9646fba2ee82bab.
close #이슈번호
> Revert "hotfix: feat: 전시회 좋아요 토글 낙관적 업데이트 (#199)"

- hooks/useUserAuthActions/index.ts
- pages/_app.tsx
- utils/tokenManager/index.ts
> fix: _app 에서 접근하지 못하는 코드 삭제

- pages/users/[id]/index.tsx
> refactor: ReviewCard에 전달하는 photos 수정

- components/organisms/Swiper/index.tsx
- pages/index.tsx
구현 화면은 이전과 같습니다!
최대한 가독성있게 적어보려고 노력했습니다! 잘 쓴걸까요..? ㅎㅎ  
혹시 부족한 부분이 있다면 언제든지 편하게 말해주세용 ! 적극 반영하겠습니다아 🙃
close #213
> feat: 메인페이지 getServersideProps 도입

- components/molecules/ReviewExhibitionInfo/index.tsx
- components/molecules/ReviewExhibitionInfo/style.ts
- components/organisms/CommentList/index.tsx
- components/organisms/CommentUtils/index.tsx
- components/organisms/CommentWrite/index.tsx
- components/organisms/ReviewDetail/index.tsx
- components/organisms/ReviewDetail/style.ts
- hooks/useUserAuthActions/index.ts
- pages/reviews/detail/[id]/index.tsx
- types/apis/user/index.ts
- types/model.ts
> design: 리뷰 디테일 페이지 반응형 작업

- pages/reviews/detail/[id]/index.tsx
- 동작은 이전 동작과 같습니다. 뭔가 빨라진 느낌? 이네요 ㅎㅎ
close #244
> feat: 리뷰 디테일 페이지 csr로직 swr로 변경

- components/molecules/ExhibitionCard/style.ts
- components/organisms/Swiper/index.tsx
- hooks/useWindowSize/index.ts
> feat: 스와이퍼 및 ExhibitionCard 반응형 추가
